variables:
- name: 'analysis-services-flag'
  value: '1'
- name: 'cosmos-db-flag'
  value: '1'
- name: 'data-catalog-flag'
  value: '1'
- name: 'data-factory-flag'
  value: '1'
- name: 'data-lake-flag'
  value: '1'
- name: 'event-grid-flag'
  value: '1'
- name: 'event-hub-flag'
  value: '1'
- name: 'function-flag'
  value: '1'
- name: 'logic-app-flag'
  value: '1'
- name: 'redis-cache-flag'
  value: '1'
- name: 'service-bus-flag'
  value: '1'
- name: 'sql-db-flag'
  value: '1'
- name: 'sql-db-mi-flag'
  value: '1'
- name: 'sql-server-flag'
  value: '1'
- name: 'storage-account-flag'
  value: '1'
- name: 'stream-analytics-flag'
  value: '1'
- name: 'synapse-flag'
  value: '1'
