variables:
- group: 'smoke-variables'
- name: 'ev'
  value: 'tst'
- name: 'location'
  value: 'East US'
- name: 'location-key'
  value: 'eastus'
- name: 'org-tag'
  value: 'azs'
- name: 'resource-group'
  value: 'rg-smoke'
- name: 'sqlServerAdminPassword'
  value: 'changeme'
- name: 'suffix'
  value: 'eus'