parameters:
  armTemplateFile: ''
  armParameterTemplateFile: ''
  location: ''
  ev: ''
  AzureSubscription: ''
  resourceGroup: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'deploy-data-factory'
  inputs:
    AzureSubscription: ${{ parameters.AzureSubscription }}
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: ${{ parameters.location }}
    csmFile: '${{ parameters.armTemplateFile }}'
    csmParametersFile: '${{ parameters.armParameterTemplateFile }}'
    overrideParameters: '-ResourceGroupName ${{ parameters.resourceGroup }} -Env ${{ parameters.ev }}'
    deploymentName: 'deployment-data-factory'
    deploymentOutputs: armOutput
  condition: and(succeeded(), eq(variables['data-factory-flag'], '1'))
