parameters:
  armTemplateFile: ''
  armParameterTemplateFile: ''
  location: ''
  ev: ''
  AzureSubscription: 'azure-devops-service-connection'
  resourceGroup: ''
  storage-account-name: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'deploy-storage-account-container'
  inputs:
    AzureSubscription: ${{ parameters.AzureSubscription }}
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: ${{ parameters.location }}
    csmFile: '${{ parameters.armTemplateFile }}'
    csmParametersFile: '${{ parameters.armParameterTemplateFile }}'
    overrideParameters: '-ResourceGroupName ${{ parameters.resourceGroup }} -Env ${{ parameters.ev }}'
    deploymentName: 'deployment-storage-account-container'
    deploymentOutputs: armOutput
  condition: and(succeeded(), eq(variables['storage-account-flag'], '1'))
