parameters:
  armTemplateFile: ''
  armParameterTemplateFile: ''
  location: ''
  ev: ''
  azureSubscription: ''
  resourceGroup: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'deploy-logic-app'
  continueOnError: true
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: ${{ parameters.location }}
    csmFile: '${{ parameters.armTemplateFile }}'
    csmParametersFile: '${{ parameters.armParameterTemplateFile }}'
    overrideParameters: '-ResourceGroupName ${{ parameters.resourceGroup }} -Env ${{ parameters.ev }}'
    deploymentName: 'deployment-logic-app'
    deploymentOutputs: armOutput
    # no change made
  condition: and(succeeded(), eq(variables['logic-app-flag'], '1'))
