parameters:
  armTemplateFile: ''
  armParameterTemplateFile: ''
  location: ''
  ev: ''
  AzureSubscription: 'azure-devops-service-connection'
  resourceGroup: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'deploy-event-hub-hub'
  inputs:
    AzureSubscription: ${{ parameters.AzureSubscription }}
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: ${{ parameters.location }}
    csmFile: '${{ parameters.armTemplateFile }}'
    csmParametersFile: '${{ parameters.armParameterTemplateFile }}'
    overrideParameters: '-ResourceGroupName ${{ parameters.resourceGroup }} -Env ${{ parameters.ev }}'
    deploymentName: 'deployment-event-hub-hub'
    deploymentOutputs: armOutput
  condition: and(succeeded(), eq(variables['event-hub-flag'], '1'))