parameters:
  azureSubscription: ''
  resourceGroup: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'remove-resource-group'
  continueOnError: true
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    action: DeleteRG
    resourceGroupName: '$(resource-group)'
    deploymentName: 'deployment-remove-rg'
  condition: and(succeeded(), eq(variables['purge-rg-smoketest'], '1'))

